/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import domain.Vehiculo;
import java.util.ArrayList;
import data.Persistencia;
import domain.Marca;
import domain.Sucursal;
import domain.VehiculoCombustible;
import domain.VehiculoElectrico;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author valentin
 */
public class RegitrarVehiculoView extends javax.swing.JFrame {

    /**
     * Creates new form RegitrarVehiculoView
     */
    private static ArrayList<Vehiculo> vehiculos = new ArrayList<>();
    
    public static ArrayList<Vehiculo> getVehiculos(){
        return vehiculos;
    }
    
    public static Optional<Vehiculo> getVehiculo(String patente){
        return vehiculos.stream()
                .filter(v -> v.getPatente().equals(patente))
                .findFirst();
    }
    
    public RegitrarVehiculoView() {
        initComponents();
        
        
        jComboMarca.removeAllItems();
        jComboMarca.addItem("Seleccionar marca...");
        ArrayList<Marca> listaMarcas = Persistencia.getMarcas();
        for (Marca m : listaMarcas) {
            jComboMarca.addItem(m.getNombre());
        }
        
        jComboBoxSucursal.removeAllItems();
        jComboBoxSucursal.addItem("Seleccionar sucursal...");
        ArrayList<Sucursal> listaSucursales = Persistencia.getSucursales();
        for (Sucursal s : listaSucursales) {
            jComboBoxSucursal.addItem(s.getCodigo());
            
        }
        
        jComboBoxTipos.removeAllItems();
        jComboBoxTipos.addItem("Seleccionar tipo...");
        jComboBoxTipos.addItem("ELECTRICO");
        jComboBoxTipos.addItem("COMBUSTIBLE");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneRegistro = new javax.swing.JDesktopPane();
        jComboMarca = new javax.swing.JComboBox<>();
        jComboBoxSucursal = new javax.swing.JComboBox<>();
        jLabelPatente = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jTextFieldPatente = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabelAnio = new javax.swing.JLabel();
        jTextFieldAnio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabelExtra = new javax.swing.JLabel();
        jTextFieldExtra = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jTextFieldConsumo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Vehiculo");

        jComboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboMarca.setPreferredSize(new java.awt.Dimension(72, 20));
        jComboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMarcaActionPerformed(evt);
            }
        });

        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSucursal.setToolTipText("");
        jComboBoxSucursal.setPreferredSize(new java.awt.Dimension(72, 20));
        jComboBoxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSucursalActionPerformed(evt);
            }
        });

        jLabelPatente.setText("Patente:");

        jLabelModelo.setText("Modelo");

        jLabelAnio.setText("Año:");

        jLabel1.setText("Cap. Carga:");

        jTextFieldCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargaActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca:");

        jLabel3.setText("Sucursal:");

        jComboBoxTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Tipo:");

        jLabelExtra.setText("Consumo adicional: ");

        jButtonCancelar.setText("Cancelar Registro");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Finalizar Registro");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Km / L :");

        jDesktopPaneRegistro.setLayer(jComboMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jComboBoxSucursal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabelPatente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabelModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jTextFieldPatente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jTextFieldModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabelAnio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jTextFieldAnio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jTextFieldCarga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jComboBoxTipos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabelExtra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jTextFieldExtra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jButtonCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jButtonRegistrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jTextFieldConsumo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneRegistro.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneRegistroLayout = new javax.swing.GroupLayout(jDesktopPaneRegistro);
        jDesktopPaneRegistro.setLayout(jDesktopPaneRegistroLayout);
        jDesktopPaneRegistroLayout.setHorizontalGroup(
            jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrar))
                    .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                                .addComponent(jTextFieldCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelPatente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPaneRegistroLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPatente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jTextFieldModelo)
                                        .addComponent(jTextFieldAnio))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                                .addComponent(jLabelExtra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldExtra, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))))
                .addGap(43, 43, 43))
        );
        jDesktopPaneRegistroLayout.setVerticalGroup(
            jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneRegistroLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPatente)
                            .addComponent(jTextFieldPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo)
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnio)
                            .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPaneRegistroLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jDesktopPaneRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonRegistrar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneRegistro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneRegistro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        String patente = jTextFieldPatente.getText();
        String modelo = jTextFieldModelo.getText();
        int anio = Integer.parseInt(jTextFieldAnio.getText());
        double cap = Double.parseDouble(jTextFieldCarga.getText());
        double extra = Double.parseDouble(jTextFieldExtra.getText());

        int marca = jComboMarca.getSelectedIndex()-1;
        int suc = jComboBoxSucursal.getSelectedIndex()-1;

        ArrayList<Marca> marcas = Persistencia.getMarcas();
        Marca m = marcas.get(marca);

        ArrayList<Sucursal> sucursales = Persistencia.getSucursales();
        Sucursal s = sucursales.get(suc);

        if (jComboBoxTipos.getSelectedIndex()==1) {    
            if (extra >=0 && extra <100) {
                VehiculoElectrico v = new VehiculoElectrico(patente, m, modelo, anio, cap, s, extra);
                vehiculos.add(v);
            }
        }

        if (jComboBoxTipos.getSelectedIndex()==2) {
            double consumo = Double.parseDouble(jTextFieldConsumo.getText());
            if (extra < 10) {
            VehiculoCombustible v = new VehiculoCombustible(patente, m, modelo, anio, cap, s, consumo, extra);
            vehiculos.add(v);
            }
        }        
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jComboBoxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSucursalActionPerformed

    private void jComboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMarcaActionPerformed

    private void jTextFieldCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegitrarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegitrarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegitrarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegitrarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegitrarVehiculoView().setVisible(true);
            }
        });
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxSucursal;
    private javax.swing.JComboBox<String> jComboBoxTipos;
    private javax.swing.JComboBox<String> jComboMarca;
    private javax.swing.JDesktopPane jDesktopPaneRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelExtra;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPatente;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldCarga;
    private javax.swing.JTextField jTextFieldConsumo;
    private javax.swing.JTextField jTextFieldExtra;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPatente;
    // End of variables declaration//GEN-END:variables
}
